spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: javatechie.learning@gmail.com
    password: ityb qgge wjfb lstj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9191